name: Aggiorna estrazioni

on:
  workflow_dispatch:

  schedule:
    # Controllo mattutino:
    # 07:00 ora italiana sia solare che legale
    - cron: "0 5,6 * * *"

    # Fascia MillionDAY 13:00:
    # copre ora solare + ora legale
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 11-13 * * *"

    # Controllo di sicurezza pomeridiano:
    # 16:30 ora italiana sia solare che legale
    - cron: "30 14,15 * * *"

    # Fascia serale:
    # copre ora solare + ora legale
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 18-20 * * *"

permissions:
  contents: write

jobs:
  aggiorna:
    runs-on: ubuntu-latest

    steps:
      - name: Scarica repository
        uses: actions/checkout@v4

      - name: Imposta Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installa dipendenze
        run: pip install requests beautifulsoup4

      - name: Esegui aggiornamento
        run: python update_data.py

      - name: Salva data.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git diff --cached --quiet || git commit -m "Aggiornamento estrazioni"
          git push
